### ISSUE TITLE
Core.js:5760 ERROR TypeError: Cannot assign to read only property 'tView' of object '[object Object]'

### ISSUE THREAD

**Issue by Robbie106gti** [ngrx/platform#2109]
## Minimal reproduction of the bug/regression with instructions:
I came across a compatibility issue with NgRx and Angular Version 9 Router

step 1: created a new CLI () project and add NgRx store, effects, entity, router-store, store, store-devtools
"@angular/cli": "^9.0.0-next.3"
"@angular/compiler-cli": "^9.0.0-next.5"

step 2: Make sure to use Ivy renderer
https://fireship.io/snippets/angular-upgrade-with-ivy/

step 3: create some routes

error in console when trying to navigate:
core.js:5760 ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'tView' of object '[object Object]'
TypeError: Cannot assign to read only property 'tView' of object '[object Object]'

## Expected behavior:
moving between routes

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
windows 10, node v10.14
    "@angular/animations": "^9.0.0-next.5",
    "@angular/common": "^9.0.0-next.5",
    "@angular/compiler": "^9.0.0-next.5",
    "@angular/core": "^9.0.0-next.5",
    "@angular/forms": "^9.0.0-next.5",
    "@angular/platform-browser": "^9.0.0-next.5",
    "@angular/platform-browser-dynamic": "^9.0.0-next.5",
    "@angular/platform-server": "^9.0.0-next.5",
    "@angular/router": "^9.0.0-next.5",
    "@ngrx/effects": "^8.3.0",
    "@ngrx/entity": "^8.3.0",
    "@ngrx/router-store": "^8.3.0",
    "@ngrx/store": "^8.3.0",
    "@ngrx/store-devtools": "^8.3.0",
    "core-js": "^2.6.9",
    "rxjs": "^6.3.3",
    "tslib": "^1.9.0",
    "zone.js": "^0.8.29"

## Other information:
app.module.ts

    StoreModule.forRoot(reducers, {
      metaReducers,
      runtimeChecks: { <-- delete this object and everythings fine...
        strictStateImmutability: true,  <-- this property seems to be interfering
        strictActionImmutability: true <-- this property seems to be interfering
      }
    }),

Sorry if i did this wrong but this is my first time and just wanted to let you.

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by Robbie106gti** [comment]
Wanted to add that having all 4 properties there also fixes the issue

        strictStateImmutability: true,
        strictActionImmutability: true,
        strictStateSerializability: true,
        strictActionSerializability: true,

**Comment by timdeschryver** [comment]
Hmmm, it's weird that if you have all the checks turned on it doesn't occur.
Do you got/can create a reproduction of this behavior?

**Comment by timdeschryver** [comment]
You must use the `minimal` flag if you want the checks enabled, see https://ngrx.io/guide/router-store/configuration for more info.

**Comment by tonivj5** [comment]
I have found this error too, updating to angular 9. Why was it closed? It was hard to relate to `ngrx`.

I have opened an issue at angular repo (https://github.com/angular/angular/issues/34993) because the error pointed me to it at first instance. Once, I have found that `@ngrx/router-store` was the culprit I have found this issue :sob: (it has been a very long day...)

**Comment by AndrewKushnir** [comment]
Hi,

I'd like to followup [on the issue](https://github.com/angular/angular/issues/34993) @tonivj5 created in Angular Framework repo and provide more info after additional investigation. You can repro this issue using this repo: https://github.com/tonivj5/angular-issue-34993 (thanks @tonivj5).

The problem appears when the `strictActionImmutability` flag is set in the `StoreModule.forRoot` call, thus causing action payloads to become frozen recursively. Navigation event also contains a reference to a Component and as a result, all fields (including Ivy defs generated for that component, i,e. `ɵcmp`) become frozen. This is problematic for Ivy runtime, since it uses this def and expects it to be writable. As a result, when Ivy runtime tries to write to `ɵcmp` field (or one of the nested fields inside that data structure), an error is thrown saying that a given field is read-only. I'm attaching a screen shot with additional information and specific part of code where it happens, see below.

<img width="1314" alt="ngrx-freezes-cmp" src="https://user-images.githubusercontent.com/43554145/73897197-25574200-483a-11ea-87b5-1174215ab752.png">

As a possible solution, fields with names starting with `ɵ` (used to annotate private Angular fields/API) might be excluded from "freeze" operation.

// cc @robwormald 

Thank you.

**Comment by garrappachc** [comment]
+1 for this. In my project I neede to disable the `strictActionImmutability` check: https://github.com/tf2pickup-pl/client/commit/81a82c8e85d71eb90059446cdb1fc30ac253c3e5
With this check disabled, everything works fine.
I have no idea why this issue is closed, it is obviously still affecting all projects that want to move to Angular 9.

**Comment by brandonroberts** [comment]
@garrappachc this issue has been fixed in master, and will go out with the next release soon. If we need to cut a bug fix for NgRx 8.x before then we will do that also.

**Comment by ChrisMeeusen** [comment]
> +1 for this. In my project I needed to disable the `strictActionImmutability` check: [tf2pickup-pl/client@81a82c8](https://github.com/tf2pickup-pl/client/commit/81a82c8e85d71eb90059446cdb1fc30ac253c3e5)
> With this check disabled, everything works fine.
> I have no idea why this issue is closed, it is obviously still affecting all projects that want to move to Angular 9.

Updated to ng 9.0.2 today and this workaround got me running.  Thanks!

**Comment by pburkindine** [comment]
@brandonroberts @AndrewKushnir  I am still experiencing this issue in A9.  I have tried disabling both strictState and strictAction, and also upgrading to ngrx@9.0.0-beta.1

Our use case is this: various nx modules are passing a Type<SomeComponent> through state to the app.component, where the component is factoried into a MatSidenavContainer.

I also tried passing the factory instead and received a similar error.

This is a major problem for us; I don't want to have to revert after a long week getting us to A9.  Please let me know what information I can provide.

**Comment by tonivj5** [comment]
besides disabling strictAction and strictState try using minimal router state:
```ts
StoreRouterConnectingModule.forRoot({ routerState: RouterState.Minimal }),
```

**Comment by dalu** [comment]
This issue is closed but it's still an issue, even with ngrx* v9.0.0

**Comment by timdeschryver** [comment]
@dalu see #2404

**Comment by kkuriata** [comment]
Are you going to fix this issue? The app keeps crashing with newest Angular 9.0.6 and NgRx 9.0.0. Setting `strictActionImmutability` solves a problem, but this workaround is not a proper solution...

**Comment by dalu** [comment]
If the fix was that simple it would've been done by now, seeing that this is an active project.
Did you bother to read 1 line above your comment and see that issue and the comments in there? 
```




  ## ##    #######  ##          #####   ##        
  ## ##   ##     ## ##    ##   ##   ##  ##    ##  
#########        ## ##    ##  ##     ## ##    ##  
  ## ##    #######  ##    ##  ##     ## ##    ##  
######### ##        ######### ##     ## ######### 
  ## ##   ##              ##   ##   ##        ##  
  ## ##   #########       ##    #####         ##  



                       


```

**Comment by curiouscod3** [comment]
In my case, I had to set to false both to get rid of the error:

> strictStateImmutability: false,
>  strictActionImmutability: false,

But, this wouldn't be alternative solution.

**Comment by tiaguinho** [comment]
Hi @brandonroberts this is still happening with me in the latest version of NGRX.
Could you please reopen the issue?

**Comment by helzgate** [comment]
Using the latest version of ngrx 9.1.2 I still got this error.  I had to change the following line:

    StoreRouterConnectingModule.forRoot({ serializer: DefaultRouterStateSerializer, stateKey: 'router' }),

to:

    StoreRouterConnectingModule.forRoot({ stateKey: 'router' }),

This was code from a Metronic theme written for Ang8 I was upgrading to Ang9.

**Comment by SheppardX** [comment]
I have version ngrx 9.1.2 and angular 9.1.9 and i get these error inside of a reducer and with 

`  StoreModule.forRoot(appReducers, {
    runtimeChecks: {
      strictStateImmutability: false,
      strictActionImmutability: false,
      // disabled until https://github.com/ngrx/platform/issues/2109 is resolved
      /* strictActionImmutability: true, */
    },
  }),`

its working again. 

for me the problem occur on a "ToDo" list i click on the check and then i call an endpoint and set the new data in the reducer and update the store and on updated the store in the Success Action i get the readonly Property error

**Comment by PolanZ** [comment]
app.module.ts
```
import: [
  StoreModule.forRoot({}),
]
```

test.module.ts

```
StoreModule.forFeature('test', reducer)
```

like that, how to do!

**Comment by manojmess** [comment]
> Wanted to add that having all 4 properties there also fixes the issue
> 
> ```
>     strictStateImmutability: true,
>     strictActionImmutability: true,
>     strictStateSerializability: true,
>     strictActionSerializability: true,
> ```


	                        strictStateImmutability: true,
				strictActionImmutability: true,
				strictStateSerializability: false,
				strictActionSerializability: true,
				
				this works fine for me

**Comment by manojmess** [comment]
> ## Minimal reproduction of the bug/regression with instructions:
> I came across a compatibility issue with NgRx and Angular Version 9 Router
> 
> step 1: created a new CLI () project and add NgRx store, effects, entity, router-store, store, store-devtools "@angular/cli": "^9.0.0-next.3" "@angular/compiler-cli": "^9.0.0-next.5"
> 
> step 2: Make sure to use Ivy renderer https://fireship.io/snippets/angular-upgrade-with-ivy/
> 
> step 3: create some routes
> 
> error in console when trying to navigate: core.js:5760 ERROR Error: Uncaught (in promise): TypeError: Cannot assign to read only property 'tView' of object '[object Object]' TypeError: Cannot assign to read only property 'tView' of object '[object Object]'
> 
> ## Expected behavior:
> moving between routes
> 
> ## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):
> windows 10, node v10.14 "@angular/animations": "^9.0.0-next.5", "@angular/common": "^9.0.0-next.5", "@angular/compiler": "^9.0.0-next.5", "@angular/core": "^9.0.0-next.5", "@angular/forms": "^9.0.0-next.5", "@angular/platform-browser": "^9.0.0-next.5", "@angular/platform-browser-dynamic": "^9.0.0-next.5", "@angular/platform-server": "^9.0.0-next.5", "@angular/router": "^9.0.0-next.5", "@ngrx/effects": "^8.3.0", "@ngrx/entity": "^8.3.0", "@ngrx/router-store": "^8.3.0", "@ngrx/store": "^8.3.0", "@ngrx/store-devtools": "^8.3.0", "core-js": "^2.6.9", "rxjs": "^6.3.3", "tslib": "^1.9.0", "zone.js": "^0.8.29"
> 
> ## Other information:
> app.module.ts
> 
> ```
> StoreModule.forRoot(reducers, {
>   metaReducers,
>   runtimeChecks: { <-- delete this object and everythings fine...
>     strictStateImmutability: true,  <-- this property seems to be interfering
>     strictActionImmutability: true <-- this property seems to be interfering
>   }
> }),
> ```
> 
> Sorry if i did this wrong but this is my first time and just wanted to let you.
> 
> ## I would be willing to submit a PR to fix this issue
> [x] Yes (Assistance is provided if you need help submitting a pull request) [ ] No

	strictStateImmutability: true,
				strictActionImmutability: true,
				strictStateSerializability: false,
				strictActionSerializability: true,
