### ISSUE TITLE
Docs: @ngrx/entity overview page contains broken link to redux's FAQ

### ISSUE THREAD

**Issue by talohana** [ngrx/platform#2310]
## Info

The [overview page](https://ngrx.io/guide/entity) of @ngrx/entity contains a [broken link](https://redux.js.org/faq/organizingstate#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) when referring to redux's FAQ when instead should be [this](https://redux.js.org/faq/organizing-state/#can-i-put-functions-promises-or-other-non-serializable-items-in-my-store-state) link

## I would be willing to submit a PR for the docs :heart:

[X] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

**Comment by timdeschryver** [comment]
Feel free to grab this one @talohana if you want (mention it here if you do)

**Comment by talohana** [comment]
@timdeschryver yeah I will create PR for that

**Comment by timdeschryver** [comment]
Awesome, thanks! If there's something that we can help with, feel free to ask for help.

**Comment by talohana** [comment]
I see it's already fixed at b1e1bee188112c46b5918e68e9f9a214acc6ee4d, somehow I couldn't find issue linked to it.  
I'll have my first PR next time :sweat_smile:

**Comment by timdeschryver** [comment]
From what I can see that PR does not fix the broken link @talohana

**Comment by talohana** [comment]
@timdeschryver okay then, I'll open or later today/tomorrow

**Comment by timdeschryver** [comment]
Fyi, the page that we have to edit can be found at https://github.com/ngrx/platform/edit/master/projects/ngrx.io/content/guide/entity/index.md?message=docs%3A%20describe%20your%20change...

**Comment by talohana** [comment]
I inspected the code again, de703f0 fixed it, somehow I got the wrong commit hash
Sorry about that!

**Comment by brandonroberts** [comment]
Fixed via https://github.com/ngrx/platform/pull/2297
